# Sử dụng một base image với Node.js
FROM node:latest

# Thiết lập thư mục làm việc trong container
WORKDIR /usr/src/apiGateway

# Sao chép package.json và package-lock.json vào thư mục làm việc
COPY package*.json ./

# Cài đặt các dependencies
RUN npm install

# Sao chép toàn bộ mã nguồn
COPY . .

# Command để chạy userService
CMD ["npm", "start"]

